### ISSUE TITLE
run.js uses nonexistent "shortHelp" property

### ISSUE THREAD

**Issue by brentdax** [heroku/heroku-cli-util#1]
The command list printing code at [run.js line 12](https://github.com/heroku/heroku-cli-util/blob/master/run.js#L12) tries to print a `shortHelp` property from the command object, but neither of the example plugins provides such a string, and `heroku-cli`'s [Command struct](https://github.com/heroku/heroku-cli/blob/dev/command.go#L13) doesn't have such a field. If I had to guess, I'd say that this project should use the `description` field instead, but it's possible that I've misunderstood the meaning of the various help-related keys, or that `shortHelp` is correct and everything else should be updated instead.

**Comment by dickeyxxx** [comment]
closing since run.js was removed
