### ISSUE TITLE
API Caching

### ISSUE THREAD

**Issue by jdx** [heroku/heroku-cli-util#64]
I think it would be useful, especially for slow commands like `heroku addons` and `heroku dashboard` if the CLI cached some common requests.

`heroku-client` already supports caching, we could store them in `XDG_CACHE_HOME/heroku`, so this change wouldn't be hard.

There may be some security (not serious ones, the `.netrc` file is already on disk) and disk space implications of caching everything indiscriminately, so a whitelist of only items we want to cache is important here. We probably want to chmod the files down to 0600 as well.

This depends on the result of https://github.com/heroku/node-heroku-client/issues/66 I think. I want to make sure we get the caching right before just slapping this in.

**Comment by dickeyxxx** [comment]
cc @heroku/ecosystem
